name: Develop pre-Release

on:
  push:
    branches-ignore: master      
  create:
    tags:
      - v*.*.*-pre
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2  
      
    - name: Set env
      run: echo "REPO_TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install dependencies
      run: dotnet restore src/HSMServer/HSMServer.sln
      
    - name: Build
      run: dotnet build src/HSMServer/HSMServer.sln --configuration Release --no-restore --output '${{ github.workspace }}\Release'  
            
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}\Release
        name: Release    
        
  publish-pre-release:
    runs-on: ubuntu-latest
    needs: build
    environment: DockerHub
    steps:
      - uses: actions/checkout@v2
          
      - name: Test
        run: |
          echo $REPO_TAG
          echo ${{ env.REPO_TAG }}
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: Release
          path: ${{ github.workspace }}/Release                             
