name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    #- name: print tag
      #run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV            
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore HSMServer/HSMServer.sln
      
    - name: Build
      run: dotnet build HSMServer/HSMServer.sln --configuration Release --no-restore --output '${{ github.workspace }}\Release'  
      
    - name: Install Client Dependencies
      run: dotnet restore HSMClient/HSMClient.sln
      
    - name: Build Client
      run: dotnet build HSMClient/HSMClient.sln --configuration Release --no-restore --output '${{ github.workspace }}\Release\Client
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}\Release
        name: Release
  
  build_NuGet:
    runs-on: windows-latest
    environment: Nuget  
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Intall nuget
        uses: nuget/setup-nuget@v1
        with: 
          nuget-api-key: ${{ secrets.NUGETKEY }}
          
      #- name: Publish data collector
      #  uses: rohith/publish-nuget@v2
      #  with:
      #    PROJECT_FILE_PATH: HSMDataCollector/HSMDataCollector/HSMDataCollector.csproj
      #    NUGET_KEY: ${{ secrets.NUGETKEY }}
      #    VERSION_STATIC: 1.0.5
      - name: Install nuget package dependencies
        run: dotnet restore HSMDataCollector/HSMDataCollector.sln
      - name: build package one
        run: dotnet build HSMDataCollector/HSMDataCollector/HSMDataCollector.csproj --configuration Release
      - name: Run pack
        run: dotnet pack HSMDataCollector/HSMDataCollector/HSMDataCollector.csproj --output ${{ github.workspace }}\nugetFolder --configuration Release -p:PackageVersion=1.0.5
      - name: Show packed structure
        run: Tree ${{ github.workspace }}\nugetFolder
      - name: Push
        run: dotnet nuget push ${{ github.workspace }}\nugetFolder\HSMDataCollector.1.0.5.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: DockerHub
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: Release
          path: ${{ github.workspace }}/Release
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}/Release
        
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master              
        with:
          name: hsmonitoring/hierarchical_sensor_monitoring
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}      
          tags: "latest"
