name: DataCollector Nuget package build

on:
  push:
      branches:
        - develop

jobs:
  build_NuGet:
    runs-on: ubuntu-latest
    environment: Nuget
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Intall nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}
      - name: Set env
        run: echo "RELEASE_VERSION=${{ needs.version.outputs.version-tag }}" >> $GITHUB_ENV


      - name: Update nugets and dependecies
        run: dotnet restore src/HSMSensorDataObjects/HSMSensorDataObjects.csproj

      - name: Build Sensor objects
        run: dotnet build src/HSMSensorDataObjects/HSMSensorDataObjects.csproj --configuration Release

      - name: Push nuget package
        # run: dotnet nuget push src/HSMSensorDataObjects/bin/Release/HSMSensorDataObjects*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json
        run: nuget push src/HSMSensorDataObjects/bin/Release/HSMSensorDataObjects*.nupkg ${{ secrets.NUGETKEY }} -Source https://api.nuget.org/v3/index.json