name: DataCollector Nuget package build

on:
  push:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.get-tag.outputs.parsedTag }}
    steps:
      - name: set raw tag
        run: echo "RAW_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: split-by
        id: split
        uses: rishabhgupta/split-by@v1.0.1
        with:
          string: '${{ env.RAW_TAG }}'
          split-by: 'v'

      - name: print tag
        run: echo ${{ steps.split.outputs._1 }}

      - id: get-tag
        run: echo "::set-output name=parsedTag::${{ steps.split.outputs._1 }}"

  build_NuGet:
    needs: [version]
    runs-on: ubuntu-latest
    environment: Nuget
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Intall nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}
      - name: Set env
        run: echo "RELEASE_VERSION=${{ needs.version.outputs.version-tag }}" >> $GITHUB_ENV


      - name: Update nugets and dependecies
        uses: dotnet restore .\src\HSMSensorDataObjects\HSMSensorDataObjects.csproj

      - name: Build Sensor objects
        run: dotnet build .\src\HSMSensorDataObjects\HSMSensorDataObjects.csproj --configuration Release

      - name: Push nuget package
        run: dotnet nuget push .\src\HSMSensorDataObjects\bin\Release\HSMSensorDataObjects*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json