name: DataCollector Nuget package build

on:
  push:
      branches:
        - develop

jobs:
  build_NuGet:
    runs-on: ubuntu-latest
    environment: Nuget
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Intall nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}
      - name: Set env
        run: echo "RELEASE_VERSION=${{ needs.version.outputs.version-tag }}" >> $GITHUB_ENV

      - name: Restore dependencies, build and pack package
        run: dotnet pack /src/HSMSensorDataObjects/HSMSensorDataObjects.csproj -p:PackageID=HSMDataCollector.HSMSensorDataObjects -c Release

      - name: Push nuget package
        run: dotnet nuget push src/HSMSensorDataObjects/bin/Release/HSMDataCollector.HSMSensorDataObjects*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json