name: Sandbox build
on:
  push:
    branches:
      - test_github_actions

  workflow_dispatch:
    inputs:
      isPreRelease:
        description: 'PreRelease'
        type: boolean
        required: true
        default: false
env:
  OUTPUT_FOLDER: ${{ github.workspace }}/BuildOutput

jobs:
  check-event:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ github.event_name }}"

    - if: ${{ github.event_name }} == workflow_dispatch
      run: "Is manually run"

  build:
    if: false
    runs-on: windows-latest
    outputs:
      VERSION: ${{ steps.save-version.outputs.version }}
      ARTIFACT_NAME: ${{ steps.build-artifact-name.outputs.name}}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build HSMServer
      run: dotnet build src/server/HSMServer/HSMServer.csproj -c Release -o ${{ env.OUTPUT_FOLDER }}

    - id: save-version
      name: Try to get server version
      run: echo "::set-output name=version::$((Get-Item ${{ env.OUTPUT_FOLDER }}/HSMServer.exe).VersionInfo.ProductVersion)"

    - id: build-artifact-name
      name: Build artifact name
      run: echo "::set-output name=name::HSMServer v${{ steps.save-version.outputs.version }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.OUTPUT_FOLDER }}
        name: ${{ steps.build-artifact-name.outputs.name }}


  create-tag:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      BUILD_TAG: ${{ steps.save-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - id: save-tag
        name: Create tag
        run: echo "::set-output name=tag::server-v${{ needs.build.outputs.VERSION }}"

      - name: Push tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.save-tag.outputs.tag }}
          message: "Test message"
          force_push_tag: true


  create-release:
    runs-on: ubuntu-latest
    needs: [build, create-tag]
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_FOLDER }}

      - name: Create archive name
        run: echo "ArtifactZip=HSMServer-${{ needs.build.outputs.VERSION }}.zip" >> $GITHUB_ENV

      - name: Check archive name
        run: echo $ArtifactZip

      - name: Archive artifacts
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: ${{ env.OUTPUT_FOLDER }}
          filename: ${{ env.ArtifactZip }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.build.outputs.ARTIFACT_NAME }}
          tag: ${{ needs.create-tag.outputs.BUILD_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.ArtifactZip }}
          prerelease: false
          allowUpdates: true


  publish-dockerimage:
    runs-on: ubuntu-latest
    needs: [build]
    environment: DockerHub
    env:
      DockerimageName: hsmonitoring/hierarchical_sensor_monitoring
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "${{ env.DockerimageName }}:${{ needs.build.outputs.VERSION }}"