name: Sandbox build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: windows-latest
    env:
      OutputFolder: ServerRelease
    outputs:
      VERSION: ${{ steps.save-version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build HSMServer
      run: dotnet build src/server/HSMServer/HSMServer.csproj -c Release -o $OutputFolder

    - id: save-version
      run: echo "::set-output name=version::$((Get-Item $OutputFolder/HSMServer.exe).VersionInfo.ProductVersion)"

    - name: Test
      run: echo "Project version is ${{ steps.save-version.outputs.version }}"