name: Sandbox build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: windows-latest
    env:
      OutputFolder: ${{ github.workspace }}/BuildOutput
    outputs:
      VERSION: ${{ steps.save-version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build HSMServer
      run: dotnet build src/server/HSMServer/HSMServer.csproj -c Release -o ${{ env.OutputFolder }}

    - id: save-version
      name: Try to get server version
      run: echo "::set-output name=version::$((Get-Item ${{ env.OutputFolder }}/HSMServer.exe).VersionInfo.ProductVersion)"

    - name: Print server version
      run: echo "Project version is ${{ steps.save-version.outputs.version }}"

  push_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: test-server-${{ needs.build.outputs.VERSION }}
          message: "Test message"